### ISSUE TITLE
Feature request: Lazy load

### ISSUE THREAD

**Issue by jpillora** [phuslu/geoip#1]
I'd like to  use this with https://github.com/jpillora/ipfilter though it looks like the data is parsed on import. How long does it take to load the embedded data? Wondering if it'd be worth adding a lazy-loading step?

**Comment by phuslu** [comment]
"parse data on import" happens `ips6` data expand.

![image](https://user-images.githubusercontent.com/195836/74630074-bd3b2100-5194-11ea-8f63-3bfd55ebeb83.png)

I think this is a trade off.
1. keep a simplest api (only a `geoip.Country`) and accept the overload
2. expose another lazy load method

currently I want stay option 1, thanks!

**Comment by jpillora** [comment]
At the top of your single function `geoip.County`, you do:
```go
ips6mut.Lock()
if ips6 == nil {
    initIPS6()
}
ips6mut.Unlock()
//use ips6
```

Sorry I haven't looked too deep at the generator code. I guess the remaining blobs of data are already in a usable form?

**Comment by phuslu** [comment]
Yes.

blobs are used as sorted array, `geoip.Country` just do a binary search without any memory allaction.

**Comment by jpillora** [comment]
👍
