### ISSUE TITLE
Version support

### ISSUE THREAD

**Issue by jpillora** [phuslu/geoip#2]
Importing this package currently looks like

```
require (
	github.com/phuslu/geoip v0.0.0-20200217112635-e0a14d457544
)
```

Please tag a `v1.0.0` to enable semantic/nicer-looking versioning

**Comment by phuslu** [comment]
thanks, i tag current head as v0.0.20200217
it means the geoip_db.go was updated at 2020-02-17

**Comment by jpillora** [comment]
v0 means unstable, see
https://semver.org/

Planning on updating  the API? (Excludes additions)

**Comment by phuslu** [comment]
thanks, i re-tag as v1.0.20200217
Is it OK?

**Comment by jpillora** [comment]
Yeah I guess that’ll do

**Comment by phuslu** [comment]
pkg.go.dev already updated https://pkg.go.dev/github.com/phuslu/geoip?tab=doc
